/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RTDRestaurant.View.Form.Customer_Form;

/**
 *
 * @author Admin
 */
public class AboutUs_Form extends javax.swing.JPanel {

    /**
     * Creates new form AboutUs_Form
     */
    public AboutUs_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new RTDRestaurant.View.Swing.PanelRound();
        img = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        wel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        footer = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listMember = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        header1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(222, 222, 222));

        panelRound1.setBackground(new java.awt.Color(247, 247, 247));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/aboutus.jpg"))); // NOI18N

        header.setFont(new java.awt.Font("Papyrus", 1, 20)); // NOI18N
        header.setForeground(new java.awt.Color(108, 91, 123));
        header.setText("ABOUT US");

        wel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        wel.setForeground(new java.awt.Color(63, 63, 63));
        wel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wel.setText("<html>  Welcome to  <i style=\"color:rgb(108,91,123);font-size:16px;\">  ROYAL THEDREAMERS<i> </html>");

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txt.setEditable(false);
        txt.setBackground(new java.awt.Color(255, 255, 255));
        txt.setColumns(20);
        txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt.setForeground(new java.awt.Color(89, 89, 89));
        txt.setLineWrap(true);
        txt.setRows(5);
        txt.setText("Nhà hàng của chúng tôi là biểu tượng của sự thanh lịch và sang trọng. Với kiến trúc đẹp mắt, nội thất đậm chất cổ điển và sự chú trọng đến từng chi tiết nhỏ, chúng tôi tạo ra một không gian lịch sự và đẳng cấp.\n\nĐội ngũ đầu bếp chúng tôi là những nghệ nhân ẩm thực, tạo ra những tác phẩm nghệ thuật trên đĩa. Với sự khéo léo trong việc kết hợp các hương vị, chúng tôi mang đến cho thực khách những trải nghiệm ẩm thực độc đáo và tinh tế. Chúng tôi sử dụng các nguyên liệu tươi ngon và cao cấp nhất, kết hợp với sự sáng tạo và kỹ thuật chế biến tinh tế để tạo nên những món ăn truyền thống với một phong cách hiện đại và độc đáo.\n\nNhà hàng của chúng tôi là một nơi lý tưởng để tụ họp với gia đình và bạn bè, nơi mà từng chi tiết đều được chăm chút tỉ mỉ. Không gian tiếp khách được thiết kế để tạo ra sự riêng tư và thoải mái, với ánh sáng dịu nhẹ và không gian yên tĩnh, tạo điều kiện lý tưởng để thưởng thức bữa ăn thượng hạng.\n\nĐội ngũ nhân viên phục vụ của chúng tôi, với sự chuyên nghiệp và tận tâm, sẽ đảm bảo rằng mỗi khách hàng được đối xử với sự chu đáo và sự phục vụ tận tâm. Chúng tôi sẽ tạo ra những trải nghiệm ẩm thực đáng nhớ, vượt xa mong đợi của quý khách.\n\nHãy đến và khám phá không gian thanh lịch, tinh tế và sang trọng của nhà hàng chúng tôi. Chúng tôi cam kết đem đến cho quý khách một trải nghiệm ẩm thực đẳng cấp và không gian lịch sự, để bạn có thể thưởng thức một bữa ăn ngon và có được những kỷ niệm chưa từng có.");
        txt.setWrapStyleWord(true);
        txt.setBorder(null);
        txt.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt.setFocusable(false);
        txt.setRequestFocusEnabled(false);
        txt.setSelectionColor(new java.awt.Color(255, 255, 255));
        txt.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(txt);

        footer.setBackground(new java.awt.Color(255, 255, 255));
        footer.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        footer.setForeground(new java.awt.Color(63, 63, 63));
        footer.setText("Since : 2023 - Co-founder by The Dreamers Team\n");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setFocusable(false);

        listMember.setColumns(20);
        listMember.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        listMember.setForeground(new java.awt.Color(89, 89, 89));
        listMember.setRows(5);
        listMember.setText("Team Members :\nLê Thị Ánh Hồng - Product Owner\nNguyễn Hoàng Việt - Scrum Master\nNguyễn Hoàng Phúc - Developer\nHồ Quang Đỉnh -  Developer");
        listMember.setBorder(null);
        listMember.setFocusable(false);
        jScrollPane3.setViewportView(listMember);

        jSeparator1.setBackground(new java.awt.Color(76, 76, 76));

        header1.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        header1.setForeground(new java.awt.Color(89, 89, 89));
        header1.setText("Tastes like a bit of heaven on your tongue.");
        header1.setToolTipText("");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(header))
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(footer)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                                .addComponent(header1)
                                .addGap(116, 116, 116)))))
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(footer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel footer;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel img;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea listMember;
    private RTDRestaurant.View.Swing.PanelRound panelRound1;
    private javax.swing.JTextArea txt;
    private javax.swing.JLabel wel;
    // End of variables declaration//GEN-END:variables
}
